### ISSUE TITLE
 Unable to login app

### ISSUE THREAD

**Issue by LcxAndroidwawa** [klinker24/talon-for-twitter-android#101]
Although I really don't want to ask this question ，But I really want to study the code. so 

401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
W/System.err: message - Could not authenticate you.
W/System.err: code - 32
W/System.err: Relevant discussions can be found on the Internet at:

**Comment by klinker24** [comment]
You will need to follow the instructions on the readme to generate and apply your API keys to the app

https://github.com/klinker24/talon-for-twitter-android/blob/master/readme.md
