### ISSUE TITLE
Add "Google Sans" font and other Google I/O changes

### ISSUE THREAD

**Issue by detoro84** [klinker24/talon-for-twitter-android#103]
In latest Google I/O they released Material Design "2" with some changes (rounded corners, etc) and new fonts.

It would be nice to add at least the font.

**Comment by klinker24** [comment]
Google Sans font is not open source or licensed to be included in the app, that isn't part of material theming. 

If you want to provide me with specific things you want to see, I can consider them. I can't do anything off of something this generic though. 

Rounded corners are not part of the material theming, that is Google's material theme. The point of the material theming is to customize the design for your needs and be more flexible. It isn't specifically making rounded corners.
