### ISSUE TITLE
Missing fiskurgit/ChipCloud

### ISSUE THREAD

**Issue by harshitaneja** [klinker24/talon-for-twitter-android#112]
The github repository of fiskurgit/ChipCloud is missing and thus can't build the app.

**Comment by klinker24** [comment]
Weird, looks like he removed it.

Can probably move to this as a replacement

https://github.com/DONIKAN/ChipCloud

**Comment by harshitaneja** [comment]
I tried using this. But the build fails when it can't find fisk.chipcloud.ChipCloud in ProfilePager.java and some others.
I changed it to com.adroitandroid.chipcloud.ChipCloud which worked for ChipCloud and ChipListener but not for ChipCloudConfig which is missing in this repository.

**Comment by klinker24** [comment]
I will look into replacing it, when I have some time.

**Comment by klinker24** [comment]
I just pulled the `aar` off my local maven cache. Should work fine
