### ISSUE TITLE
Add the ability to edit the API

### ISSUE THREAD

**Issue by rodrigoswz** [klinker24/talon-for-twitter-android#113]
As in [Twidere](https://github.com/TwidereProject/Twidere-Android), Talon (FOSS version) could have the ability to configure the API through the settings, making it easy for everyone to use this app.

Just compile this without configuring anything in the code.

**Comment by klinker24** [comment]
The API tokens? Sorry, that isn't planned and I am pretty confident that that would violate their terms of service. To change the tokens, you will need to compile the app yourself, sorry
