### ISSUE TITLE
Translate tweets on Android 9 Pie

### ISSUE THREAD

**Issue by jomorodion** [klinker24/talon-for-twitter-android#114]
I’ve been using Talon for quite some time now and a week ago I switched to an Oneplus 6, which runs Android 9.
The translate tweet function doesn’t work on Android 9 anymore. The redirect to translate.google.com won’t load because of the following error:

[net::ERR_CLEARTEXT_NOT_PERMITTED](https://imgur.com/a/68N6kLO).

Some search via Google make it seem like it would be an [easy fix](https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6), I’d really appreciate if someone could implement that.
Still works great on my tablet running Android 8. 

Thanks in advance!

**Comment by klinker24** [comment]
Are you using the latest version of the app? This was fixed a long time ago by using the https version of Google translate. I can confirm it works fine across all of my 9.0 devices, and that I have not heard from others on this issue.

https://github.com/klinker24/talon-for-twitter-android/blob/f938fa8cb3fad6e71df68289528bac7e78aa1567/app/src/main/java/com/klinker/android/twitter_l/settings/AppSettings.java#L501

**Comment by jomorodion** [comment]
Thanks for the fast reply!

I was in the beta program for the app and it showed 7.5.8 as the version number in the settings. I just left the beta and installed the regular one and now it works perfectly again.

The new one also shows the same version number … . I’m not sure if the beta version was the issue. I only bought the phone 7 days ago and I haven’t used Titanium backup (or something similar) for any app data from a previous version.
Anyway, it works again :).
