### ISSUE TITLE
The app constantly "Stops" when I install and try to open it

### ISSUE THREAD

**Issue by marvic2409** [klinker24/talon-for-twitter-android#119]
I built the app and put in the twitter consumer keys, but when I install it on my device (Galaxy S9 running android 9.0) the app stops. It opens to a gray screen and just stops.

**Comment by klinker24** [comment]
You would have to provide a log, for me to provide any insight. I am not seeing any issues on the production version of Talon, so I do not think it is the app.

**Comment by marvic2409** [comment]
Where can I find a log?

**Comment by klinker24** [comment]
Android Studio provides logcat output.

**Comment by marvic2409** [comment]
This is all I got:

2:14 PM	Gradle sync started

2:14 PM	Project setup started

2:15 PM	Gradle sync finished in 48 s 630 ms

2:15 PM	Executing tasks: [:wear:generateDebugSources, :shared_assets:generateDebugSources, :searchview:generateDebugSources, :app:generateDebugSources, :myapplication:generateDebugSources]

2:15 PM	Gradle build finished in 4 s 752 ms

2:18 PM	Executing tasks: [:wear:assembleDebug, :app:assembleDebug, :myapplication:assembleDebug]

2:20 PM	Gradle build finished in 1 m 58 s 162 ms

2:24 PM	Executing tasks: [:app:assembleRelease]

2:25 PM	Gradle build finished in 1 m 31 s 315 ms

2:25 PM	Generate Signed APK
				APK(s) generated successfully for 1 module:
				Module 'app': locate or analyze the APK.

**Comment by marvic2409** [comment]
Can you just tell me step by step how to compile on windows 10?

**Comment by klinker24** [comment]
I'm not going to do that, sorry. Making Android apps is not something that I can explain in the comments of a GitHub issue. There are many tutorials on Google for developing your first app, which would give you more information on Android Studio and the build process.

The app is available on Google Play. If you aren't a developer, that would be the better route to go.

**Comment by marvic2409** [comment]
Well the app compiles and it gives me no errors. I only put in the consumer api keys and not the access tokens. Is that what I did wrong? There were no areas for the access tokens

**Comment by klinker24** [comment]
I do not know what the issue is, until you post the log output. What you posted above is the build output. There is a logcat tab, describing runtime errors, in android studio.

**Comment by marvic2409** [comment]
I get this error: This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.

**Comment by marvic2409** [comment]
I am using version 3.4 and there is no version 3.5 for windows

**Comment by klinker24** [comment]
https://developer.android.com/studio/preview
