### ISSUE TITLE
How do you load all Url image in one Imageview 

### ISSUE THREAD

**Issue by anonym2** [klinker24/talon-for-twitter-android#120]
Hi  I dont understand how do you load all image inside only one Imageview , can you explain me how you do that ?

**Comment by klinker24** [comment]
This function is used to combine a list of up to 4 `Bitmap`s:

https://github.com/klinker24/talon-for-twitter-android/blob/master/app/src/main/java/com/klinker/android/twitter_l/utils/ImageUtils.java#L353

**Comment by anonym2** [comment]
Excuse me I talked about the image who are from the TimeLineCursorAdapter ho do you retrieve the list of users's image inside one imageview  , image come from String where do you convert them into bitmap ?
