### ISSUE TITLE
How do load all images in one Imageview ( More Details )

### ISSUE THREAD

**Issue by anonym2** [klinker24/talon-for-twitter-android#121]
![Screenshot_20190524-010302 1](https://user-images.githubusercontent.com/30669319/58292020-0609a900-7dc0-11e9-9277-2e30e7057798.png)

In the TimeLineCursorAdapter you loaad all images a post has inside one imageview  , how do you do that please I dont understand how its possible

**Comment by klinker24** [comment]
I am closing this as a duplicate. I already answered your question.

The function that I linked you to combines multiple bitmaps into one. You can follow it backwards to find how it is used on the timeline to combines the images into a single image view.
