### ISSUE TITLE
Could not find com.github.halilozercan:BetterVideoPlayer:1.2.alpha1

### ISSUE THREAD

**Issue by gqqnbig** [klinker24/talon-for-twitter-android#125]
I cloned the repository, added my API key to /secrets.properties, then open the folder with Android Studio 3.4.2.

Build fails and outputs error:

```
Could not find com.github.halilozercan:BetterVideoPlayer:1.2.alpha1.
Required by:
    project :app
Search in build.gradle files
```

How to fix it?

**Comment by klinker24** [comment]
Looks like that dependency (or version of the dependency, rather) was deleted. I have updated it. The build will work again.

**Comment by macearl** [comment]
Now it fails with
```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.klinker.android.twitter_l.activities.tweet_viewer.VideoFragment, unresolved supertypes: BetterVideoCallback
```

**Comment by klinker24** [comment]
Oh sorry, forgot to commit the implementation changes.

**Comment by macearl** [comment]
I think if found all of them, i assume i only had to change a couple of imports and change BetterVideoCallback to VideoCallback.

It builds now, but crashes on a timeline refresh, so maybe i missed something else
