### ISSUE TITLE
can not resolve  implementation 'com.github.fiskurgit:ChipCloud:3.0.3'

### ISSUE THREAD

**Issue by sdy8181** [klinker24/talon-for-twitter-android#127]
Hi  ,  Thank you for sharing

Android Studio always error when I import and sync this app,  the log shows can not resolve  implementation 'com.github.fiskurgit:ChipCloud:3.0.3'.

Then  I  found  that the fiskurgit/ChipCloud has been deleted from github.

So,  how can I run your app?

thanks

**Comment by klinker24** [comment]
`implementation 'com.github.fiskurgit:ChipCloud:3.0.3'` is no longer in the app. The aar is just bundled with the code now

https://github.com/klinker24/talon-for-twitter-android/blob/master/app/build.gradle#L105
https://github.com/klinker24/talon-for-twitter-android/blob/master/app/lib/ChipCloud-3.0.3.aar

This was resolved long ago. Just use the latest version of the code... #112
