### ISSUE TITLE
Increase number of accounts?

### ISSUE THREAD

**Issue by z0w13** [klinker24/talon-for-twitter-android#130]
Is there a way to easily increase the number of accounts, or has all the code been built on the concept of a primary and secondary account? (which seems to be the case from a cursory glance)

**Comment by klinker24** [comment]
It wouldn't be as simple as changing a number, no. The preferences within the app would adjust to a third account fine, but there are many places that the UI is just designed for two accounts. 

This isn't something that I plan to do on my end, sorry
