### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by techiesatish** [klinker24/talon-for-twitter-android#134]
I have used twitter Consumer Key and Secret key. But still getting `/WearActivity: connection to API client failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null} I also tried to add Youtube API KEY in the respective key but it did not resolved the issue.
`

**Comment by umbellipher** [comment]
@klinker24

IMPORTANT

>>>>> Try this (from an email I received; works for Twidere, which I now have up and running)

ConsumerKey=wmtrtTaVOjUnH5pWQp4LDI5Qs
ConsumerSecret=E9Q9u2yK0COJae2tLcNEdY75OPA3bxqJiGZQztraHaQUtoI2cu

**Comment by klinker24** [comment]
@umbellipher please don't post API keys here on GitHub. If you have keys that will work for you, feel free to build the app. I think that Twitter will disable any keys that are used at scale, as they have demonstrated with the recent change.

I have edited your comment to remove the key.

**Comment by umbellipher** [comment]
@klinker24 

I am mortified, and I apologize. A dim-witted attempt to help and show appreciation.

**Comment by klinker24** [comment]
It is no problem, just generally avoid posting any secrets to a public place
