### ISSUE TITLE
How to install on CalyxOs

### ISSUE THREAD

**Issue by BlockHackTk** [klinker24/talon-for-twitter-android#157]
Everything is in the title, there is no Google play on CalyxOs. I don't know how to install it while taking the license.

**Comment by klinker24** [comment]
This is still a paid app on Google Play, despite being open source. I do not distribute it myself outside of the Play Store. So, you can either:

1. Install from the Play Store and purchase it
2. build it from source, as this is an open source app. The instructions to do so are in the readme.
