### ISSUE TITLE
Mastodon support 

### ISSUE THREAD

**Issue by robsonsobral** [klinker24/talon-for-twitter-android#160]
It would be great if we could have a combined mastodon + twitter timeline. 

(Probably, you'll say "no", but... to ask doesn't hurt)

Thank you for your attention.

**Comment by klinker24** [comment]
I don't foresee myself adding this, no. I am not a mastodon user and don't really see a reason to add a second social media into the same app. 

That said, this app is open source and anyone could fork it and publish those changes.
