### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by alexandru-73** [klinker24/talon-for-twitter-android#90]
Hello, i can't login to Talon, i receive the following message:
```
Something went wrong... Please retry!

It could be that your date and time on your device isn't set to automatic.
This is a requirement of Twitter's 3rd party API.
```
I tried clearing data and reinstalling the app but it doesn't work.

**Comment by klinker24** [comment]
You need to set up the API keys, as described in the readme. If you get the API keys and the callback URL correct, then you will have no problem with the login.

The steps to set this up are already documented in the readme for the repo.
