### ISSUE TITLE
Crop images with custom aspect ratio 

### ISSUE THREAD

**Issue by MDXDave** [klinker24/talon-for-twitter-android#91]
Make it possible to crop images with a custom aspect ratio

**Comment by klinker24** [comment]
Talon uses [ucrop](https://github.com/Yalantis/uCrop). Might just be able to update the dependency, otherwise, this will be a much larger request.

**Comment by MDXDave** [comment]
Maybe its possible to switch to another library [Android Image Cropper](https://github.com/ArthurHub/Android-Image-Cropper)
